import NewPlatformMssqlFulltextTestStandCountryEController from '../new-platform-mssql-fulltext-test-stand-country-e';

var NewPlatformMssqlFulltextTestStandCountryENewController = NewPlatformMssqlFulltextTestStandCountryEController;
export default NewPlatformMssqlFulltextTestStandCountryENewController;
